### ISSUE TITLE
Bug: My Pet 페이지의 반려동물 정보 element 디자인 오류

### ISSUE THREAD

**Issue by PortalCube** [Likelion-MainHackaton-2team/Frontend_Dev_Repo#67]
<img src="https://github.com/Likelion-MainHackaton-2team/Frontend_Dev_Repo/assets/35104213/c21fdde5-f1e8-4d11-baf9-99b890fa9e0d" width="400"/>

펫 정보를 표시하는 박스가 왼쪽에 치우쳐져있는데, 중앙 정렬시켜야 합니당

<img src="https://github.com/Likelion-MainHackaton-2team/Frontend_Dev_Repo/assets/35104213/e6f2361a-d58f-4181-8a9a-666904506648" width="400"/>

가로 해상도가 330 이하인 기기에서는 요소가 아예 잘리는 문제도 있습니다!

**Comment by osohyun0224** [comment]
#77 해당 이슈 내용 포함 오류 수정하였습니다.
