### ISSUE TITLE
Bug: 모바일 기기에서 카테고리 선택 깨짐

### ISSUE THREAD

**Issue by PortalCube** [Likelion-MainHackaton-2team/Frontend_Dev_Repo#72]
![1691853406_l0SB_chrome](https://github.com/Likelion-MainHackaton-2team/Frontend_Dev_Repo/assets/35104213/4acc9755-c572-4d75-a2c0-c65ce8266ce2)

저 부분은 마이펫에서 펫 목록 표시하듯이 드래그 앤 드롭으로 좌우로 스크롤 되어야합니다!

마이펫에서 사용하는 Simplebar와 이름 엄청 긴 드래그앤드롭 라이브러리 적용해주시면 될 것 같습니다~

UI에서 스크롤 바 부분을 숨김 처리를 요청하셨으므로, 스크롤바 스타일에 opacity: 0 적용하면 될겁니다!!

**Comment by osohyun0224** [comment]
#76 구현완료
