### ISSUE TITLE
Feat: 메인 배너에 carousel 적용

### ISSUE THREAD

**Issue by PortalCube** [Likelion-MainHackaton-2team/Frontend_Dev_Repo#73]
![1691853606_ytel_chrome](https://github.com/Likelion-MainHackaton-2team/Frontend_Dev_Repo/assets/35104213/bf1a1af6-0b3a-4052-9f44-08d67e76ba26)

UI에서 배너 이미지를 3개 적용한다고 하셔서, carousel을 적용해야 할 것 같습니다. 직접 구현할 수도 있고 라이브러리 써도 될 듯 합니다...

**Comment by osohyun0224** [comment]
#76 배너 구현해두었습니다.
